const db = require("aa-sqlite");

async function CrearBaseSiNoExiste() {
    const dbPath = process.env.base || "./database.sqlite"; 

    await db.open(dbPath);

    let existe = false;
    let res = null;

    const sql =
        "SELECT count(*) as contar FROM sqlite_schema WHERE type = 'table' and name= 'questions'";

    res = await db.get(sql, []);
    if (res.contar > 0) existe = true;
    if (!existe) {
        await db.run(
            `CREATE table questions( 
                IdQuestion INTEGER PRIMARY KEY AUTOINCREMENT,
                Question TEXT NOT NULL,
                Opcion1 TEXT NOT NULL,
                Opcion2 TEXT NOT NULL,
                Opcion3 TEXT NOT NULL,
                Opcion4 TEXT NOT NULL,
                Correct TEXT NOT NULL
            );`
        );
        console.log("Table 'questions' created!");

        await db.run(
            `INSERT INTO questions (Question, Opcion1, Opcion2, Opcion3, Opcion4, Correct) VALUES
            ('Apoyar', 'Break down', 'Bring up', 'Back up', 'Come across', 'Back up'),
            ('Mencionar', 'Back up', 'Carry out', 'Bring up', 'Come up with', 'Bring up'),
            ('Realizar una tarea', 'Bring up', 'Carry out', 'Drop off', 'Find out', 'Carry out'),
            ('Encontrar por casualidad', 'Get along', 'Come across', 'Get over', 'Give up', 'Come across'),
            ('Idear algo', 'Look after', 'Turn out', 'Set up', 'Come up with', 'Come up with'),
            ('Dejar algo o a alguien', 'Pick up', 'Drop off', 'Set up', 'Look after', 'Drop off'),
            ('Descubrir', 'Turn out', 'Give up', 'Find out', 'Pick up', 'Find out'),
            ('Llevarse bien', 'Get along', 'Come across', 'Get over', 'Give up', 'Get along'),
            ('Superar', 'Get along', 'Give up', 'Get over', 'Drop off', 'Get over'),
            ('Rendirse', 'Find out', 'Look after', 'Give up', 'Pick up', 'Give up'),
            ('Cuidar de', 'Turn out', 'Look after', 'Back up', 'Bring up', 'Look after'),
            ('Recoger a alguien', 'Find out', 'Pick up', 'Turn out', 'Get along', 'Pick up'),
            ('Configurar algo', 'Set up', 'Come across', 'Give up', 'Look after', 'Set up'),
            ('Terminar de una manera específica', 'Get over', 'Turn out', 'Find out', 'Drop off', 'Turn out'),
            ('Aparecer inesperadamente', 'Get over', 'Turn up', 'Give up', 'Bring up', 'Turn up'),
            ('Descomponerse', 'Back up', 'Find out', 'Break down', 'Pick up', 'Break down'),
            ('Sacar un tema', 'Bring up', 'Get along', 'Look after', 'Pick up', 'Bring up'),
            ('Echarse atrás', 'Come up with', 'Drop off', 'Back down', 'Bring up', 'Back down'),
            ('Explotar', 'Back up', 'Blow up', 'Bring up', 'Pick up', 'Blow up'),
            ('Encontrarse con alguien por casualidad', 'Get over', 'Blow up', 'Drop off', 'Bump into', 'Bump into'),
            ('Cancelar', 'Call off', 'Come across', 'Look after', 'Drop off', 'Call off'),
            ('Encontrarse por casualidad', 'Look after', 'Come across', 'Give up', 'Back up', 'Come across'),
            ('Limpiar a fondo', 'Clean out', 'Bring up', 'Drop off', 'Turn out', 'Clean out'),
            ('Continuar', 'Drop by', 'Bring up', 'Carry on', 'Give up', 'Carry on'),
            ('Abandonar', 'Drop out', 'Find out', 'Get along', 'Come across', 'Drop out'),
            ('Visitar brevemente', 'Bring up', 'Look after', 'Drop by', 'Turn out', 'Drop by'),
            ('Descubrir algo', 'Turn up', 'Give up', 'Drop off', 'Find out', 'Find out'),
            ('Salir de un lugar', 'Back down', 'Get out', 'Blow up', 'Pick up', 'Get out'),
            ('Donar algo', 'Give away', 'Pick up', 'Get along', 'Turn out', 'Give away'),
            ('Superar algo', 'Get over', 'Find out', 'Give up', 'Look after', 'Get over'),
            ('Llevarse bien con alguien', 'Turn up', 'Get along', 'Pick up', 'Drop off', 'Get along'),
            ('Hacerse adulto', 'Get along', 'Grow up', 'Turn out', 'Give up', 'Grow up'),
            ('Rendirse', 'Look after', 'Give up', 'Turn out', 'Get over', 'Give up'),
            ('Salir de casa', 'Go out', 'Look after', 'Turn out', 'Bring up', 'Go out'),
            ('Continuar', 'Drop by', 'Look after', 'Go on', 'Pick up', 'Go on'),
            ('Pasar el rato', 'Hang out', 'Turn out', 'Pick up', 'Find out', 'Hang out'),
            ('Apurarse', 'Drop by', 'Hurry up', 'Get along', 'Turn out', 'Hurry up'),
            ('Recordar el pasado', 'Look after', 'Grow up', 'Give up', 'Look back', 'Look back'),
            ('Inventar', 'Make up', 'Drop by', 'Get out', 'Turn up', 'Make up'),
            ('Arruinar algo', 'Set up', 'Pick up', 'Mess up', 'Give up', 'Mess up'),
            ('Configurar algo', 'Give up', 'Set up', 'Turn out', 'Pick up', 'Set up'),
            ('Sentarse', 'Turn out', 'Sit down', 'Look after', 'Pick up', 'Sit down'),
            ('Aparecer', 'Bring up', 'Show up', 'Pick up', 'Find out', 'Show up'),
            ('Desmayarse', 'Turn down', 'Pass out', 'Pick up', 'Grow up', 'Pass out'),
            ('Recoger algo', 'Look after', 'Pick up', 'Give up', 'Turn out', 'Pick up'),
            ('Molestar a alguien', 'Turn out', 'Piss off', 'Show up', 'Get along', 'Piss off'),
            ('Señalar algo', 'Turn up', 'Pick up', 'Point out', 'Blow up', 'Point out'),
            ('Posponer', 'Give up', 'Set up', 'Put off', 'Turn out', 'Put off'),
            ('Ponerse ropa', 'Set up', 'Put on', 'Bring up', 'Drop off', 'Put on'),
            ('Encontrarse con alguien', 'Turn up', 'Run into', 'Show up', 'Pick up', 'Run into'),
            ('Despegar (un avión)', 'Pick up', 'Turn up', 'Blow up', 'Take off', 'Take off'),
            ('Rechazar algo', 'Turn down', 'Set up', 'Pick up', 'Find out', 'Turn down'),
            ('Ejercitarse', 'Watch out', 'Work out', 'Show up', 'Turn up', 'Work out'),
            ('Tener cuidado', 'Grow up', 'Give up', 'Watch out', 'Look back', 'Watch out'),
            ('Despertarse', 'Look after', 'Turn out', 'Get along', 'Wake up', 'Wake up'),
            ('Sacar algo a la luz', 'Give up', 'Bring up', 'Show up', 'Mess up', 'Bring up'),
            ('Cuidar de alguien', 'Look after', 'Wake up', 'Give up', 'Turn out', 'Look after'),
            ('Aparecer en un lugar', 'Turn up', 'Show up', 'Back up', 'Give up', 'Show up'),
            ('Dejar algo', 'Drop off', 'Give up', 'Pick up', 'Back down', 'Drop off'),
            ('Seguir adelante', 'Turn out', 'Carry on', 'Give up', 'Pick up', 'Carry on'),
            ('Caer inconsciente', 'Pass out', 'Wake up', 'Pick up', 'Drop off', 'Pass out'),
            ('Superar una situación', 'Get over', 'Look after', 'Turn up', 'Back up', 'Get over'),
            ('Inventar algo', 'Make up', 'Set up', 'Drop off', 'Give up', 'Make up'),
            ('Cancelar', 'Call off', 'Turn out', 'Look after', 'Wake up', 'Call off'),
            ('Continuar haciendo algo', 'Go on', 'Turn up', 'Get over', 'Give up', 'Go on'),
            ('Salir de un lugar', 'Get out', 'Pass out', 'Wake up', 'Pick up', 'Get out'),
            ('Pasar el rato con alguien', 'Hang out', 'Turn up', 'Pick up', 'Show up', 'Hang out'),
            ('Superar una dificultad', 'Get over', 'Drop off', 'Give up', 'Carry on', 'Get over'),
            ('Hacerse adulto', 'Grow up', 'Wake up', 'Turn out', 'Get over', 'Grow up'),
            ('Ponerse ropa', 'Put on', 'Get out', 'Pick up', 'Show up', 'Put on'),
            ('Sentarse en un lugar', 'Sit down', 'Pass out', 'Give up', 'Drop off', 'Sit down'),
            ('Llegar tarde a un lugar', 'Show up', 'Turn up', 'Get along', 'Pick up', 'Turn up'),
            ('Molestar a alguien', 'Get along', 'Piss off', 'Give up', 'Turn out', 'Piss off'),
            ('Señalar algo importante', 'Put off', 'Turn up', 'Point out', 'Drop off', 'Point out'),
            ('Posponer algo', 'Turn down', 'Put off', 'Carry on', 'Get along', 'Put off'),
            ('Ver algo importante', 'Look after', 'Watch out', 'Pick up', 'Get out', 'Watch out'),
            ('Configurar algo', 'Set up', 'Turn up', 'Drop off', 'Give up', 'Set up'),
            ('Apurarse en hacer algo', 'Hurry up', 'Show up', 'Drop by', 'Carry on', 'Hurry up'),
            ('Rechazar una oferta', 'Turn down', 'Wake up', 'Get out', 'Show up', 'Turn down'),
            ('Dejarse ver por un lugar', 'Show up', 'Turn up', 'Point out', 'Carry on', 'Turn up'),
            ('Aceptar una invitación', 'Turn down', 'Go along', 'Come along', 'Back down', 'Come along'),
            ('Aprovechar una oportunidad', 'Take up', 'Give up', 'Pick up', 'Set up', 'Take up'),
            ('Colaborar con alguien', 'Work out', 'Get along', 'Help out', 'Turn out', 'Help out'),
            ('Rechazar un plan', 'Drop out', 'Back down', 'Call off', 'Take off', 'Call off'),
            ('Darse cuenta de algo', 'Look out', 'Find out', 'Wake up', 'Turn up', 'Find out'),
            ('Ganar tiempo', 'Come up with', 'Put off', 'Hold on', 'Take up', 'Hold on'),
            ('Compartir algo', 'Pass on', 'Give up', 'Drop off', 'Look after', 'Pass on'),
            ('Confirmar un acuerdo', 'Back down', 'Set up', 'Follow up', 'Turn down', 'Follow up'),
            ('Dejar de hacer algo', 'Give up', 'Carry on', 'Drop by', 'Take off', 'Give up'),
            ('Causar problemas', 'Mess up', 'Turn down', 'Get along', 'Drop off', 'Mess up'),
            ('Preparar algo', 'Get ready', 'Look after', 'Set up', 'Turn out', 'Get ready'),
            ('Hacer las paces', 'Make up', 'Turn up', 'Call off', 'Get along', 'Make up'),
            ('Despertar a alguien', 'Wake up', 'Drop off', 'Pick up', 'Turn down', 'Wake up'),
            ('Pedir ayuda', 'Look after', 'Help out', 'Call off', 'Turn down', 'Help out'),
            ('Perder el tiempo', 'Waste time', 'Turn up', 'Hang out', 'Get along', 'Waste time'),
            ('Prometer hacer algo', 'Give up', 'Promise to', 'Come across', 'Turn down', 'Promise to'),
            ('Cambiar de opinión', 'Change mind', 'Give up', 'Take off', 'Back down', 'Change mind'),
            ('Buscar algo', 'Look for', 'Turn out', 'Pick up', 'Get along', 'Look for'),
            ('Establecer un nuevo objetivo', 'Set up', 'Take up', 'Carry on', 'Drop off', 'Set up'),
            ('Divertirse', 'Have fun', 'Get along', 'Hang out', 'Work out', 'Have fun'),
            ('Soportar algo', 'Get through', 'Back down', 'Look after', 'Drop out', 'Get through'),
            ('Revisar algo', 'Check out', 'Look for', 'Turn up', 'Call off', 'Check out'),
            ('Hacer un resumen', 'Sum up', 'Give up', 'Carry on', 'Look after', 'Sum up'),
            ('Contar una historia', 'Tell off', 'Bring up', 'Turn out', 'Bring in', 'Bring up'),
            ('Presentar a alguien', 'Introduce', 'Call off', 'Look after', 'Drop out', 'Introduce'),
            ('Hacer un seguimiento', 'Follow up', 'Back down', 'Turn down', 'Check out', 'Follow up'),
            ('Tomar una decisión', 'Make up', 'Give up', 'Decide on', 'Drop off', 'Decide on'),
            ('Salir a caminar', 'Go for a walk', 'Carry on', 'Look for', 'Drop out', 'Go for a walk'),
            ('Hacer una lista', 'List out', 'Set up', 'Check off', 'Drop off', 'List out'),
            ('Reunirse con alguien', 'Meet up', 'Call off', 'Turn down', 'Look after', 'Meet up'),
            ('Revisar el correo', 'Check in', 'Look after', 'Look for', 'Turn out', 'Check in'),
            ('Hacer ejercicio', 'Work out', 'Give up', 'Take off', 'Turn down', 'Work out'),
            ('Volver a conectar', 'Reconnect', 'Turn up', 'Hang out', 'Back down', 'Reconnect'),
            ('Cuidar a alguien', 'Look after', 'Check out', 'Give up', 'Drop off', 'Look after'),
            ('Dedicarse a algo', 'Get into', 'Take off', 'Call off', 'Set up', 'Get into'),
            ('Hablar con alguien', 'Talk to', 'Get along', 'Call off', 'Look after', 'Talk to'),
            ('Resolver un problema', 'Figure out', 'Drop out', 'Give up', 'Pick up', 'Figure out'),
            ('Ver algo de manera clara', 'See through', 'Look for', 'Find out', 'Check out', 'See through'),
            ('Acostumbrarse a algo', 'Get used to', 'Give up', 'Take off', 'Carry on', 'Get used to'),
            ('Comenzar a hacer algo', 'Give up', 'Take up', 'Carry on', 'Turn down', 'Take up'),
            ('Dejar de hacer algo', 'Give up', 'Turn down', 'Pick up', 'Look after', 'Give up'),
            ('Hacer algo más fácil', 'Turn down', 'Make up', 'Break down', 'Break up', 'Break down'),
            ('Regresar a un lugar', 'Get out', 'Come back', 'Go on', 'Call off', 'Come back'),
            ('Continuar haciendo algo', 'Carry on', 'Give up', 'Drop by', 'Look after', 'Carry on'),
            ('Encontrar algo inesperadamente', 'Run into', 'Look for', 'Come across', 'Turn up', 'Come across'),
            ('Rechazar una oferta', 'Turn down', 'Call off', 'Give up', 'Hang out', 'Turn down'),
            ('Sacar algo a la luz', 'Bring up', 'Take out', 'Set up', 'Turn up', 'Bring up'),
            ('Aumentar la velocidad', 'Speed up', 'Hold up', 'Pick up', 'Break down', 'Speed up'),
            ('Pasar tiempo con alguien', 'Hang out', 'Give up', 'Drop off', 'Pick up', 'Hang out'),
            ('Apoyar a alguien', 'Back up', 'Turn down', 'Look after', 'Carry on', 'Back up'),
            ('Comenzar a gustar algo', 'Take to', 'Give up', 'Come across', 'Turn out', 'Take to'),
            ('Posponer algo', 'Put off', 'Give up', 'Turn down', 'Drop out', 'Put off'),
            ('Seguir adelante', 'Carry on', 'Get over', 'Call off', 'Turn down', 'Carry on'),
            ('Darse cuenta de algo', 'Find out', 'Turn up', 'Look after', 'Drop off', 'Find out'),
            ('Romperse en pedazos', 'Break down', 'Fall apart', 'Hold up', 'Pick up', 'Fall apart'),
            ('Conectar algo', 'Hook up', 'Turn off', 'Set up', 'Pick up', 'Hook up'),
            ('Aguantar algo', 'Put up with', 'Give up', 'Back down', 'Drop off', 'Put up with'),
            ('Llegar a ser algo', 'Come to be', 'Get along', 'Carry on', 'Turn out', 'Come to be'),
            ('Terminar algo', 'Finish up', 'Call off', 'Give up', 'Look for', 'Finish up'),
            ('Romper con alguien', 'Break up', 'Give up', 'Turn down', 'Look after', 'Break up'),
            ('Pasar por un lugar', 'Drop by', 'Pick up', 'Call off', 'Carry on', 'Drop by'),
            ('Dejar de hacer algo', 'Give up', 'Put off', 'Take up', 'Turn down', 'Give up'),
            ('Encontrar algo por casualidad', 'Run into', 'Come across', 'Look for', 'Get along', 'Come across'),
            ('Reparar algo', 'Fix up', 'Turn up', 'Give up', 'Pick up', 'Fix up'),
            ('Dejar algo en un lugar', 'Leave behind', 'Take off', 'Drop off', 'Hang out', 'Leave behind'),
            ('Dejar de lado', 'Put aside', 'Look after', 'Pick up', 'Turn down', 'Put aside'),
            ('Despertar a alguien', 'Wake up', 'Come back', 'Turn up', 'Show up', 'Wake up'),
            ('Comenzar a trabajar en algo', 'Take on', 'Give up', 'Turn down', 'Look after', 'Take on'),
            ('Entender algo', 'Figure out', 'Get along', 'Come up with', 'Carry on', 'Figure out'),
            ('Volver a hacer algo', 'Do over', 'Give up', 'Carry on', 'Put off', 'Do over'),
            ('Deshacerse de algo', 'Get rid of', 'Turn up', 'Drop off', 'Hang out', 'Get rid of'),
            ('Entrar a un lugar', 'Come in', 'Go out', 'Get along', 'Pick up', 'Come in'),
            ('Darse cuenta de algo', 'Catch on', 'Look after', 'Give up', 'Come up with', 'Catch on'),
            ('Continuar con algo', 'Keep on', 'Turn down', 'Give up', 'Set up', 'Keep on'),
            ('Aumentar de tamaño', 'Grow up', 'Take off', 'Turn out', 'Blow up', 'Blow up'),
            ('Tomar decisiones', 'Make up', 'Figure out', 'Set up', 'Give up', 'Make up'),
            ('Iniciar una conversación', 'Bring up', 'Drop out', 'Turn down', 'Look after', 'Bring up'),
            ('Luchar contra algo', 'Fight back', 'Give up', 'Take on', 'Call off', 'Fight back'),
            ('Aguantar a alguien', 'Put up with', 'Carry on', 'Take over', 'Look after', 'Put up with'),
            ('Hacer una cita', 'Set up', 'Take on', 'Drop off', 'Call off', 'Set up'),
            ('Revelar un secreto', 'Let out', 'Bring up', 'Come across', 'Give up', 'Let out'),
            ('Aprovechar algo', 'Take advantage of', 'Give up', 'Look after', 'Turn down', 'Take advantage of'),
            ('Interrumpir', 'Break in', 'Look for', 'Run into', 'Drop by', 'Break in'),
            ('No hacer nada', 'Hang out', 'Carry on', 'Put off', 'Look after', 'Hang out'),
            ('Retroceder', 'Back down', 'Come up', 'Get over', 'Call off', 'Back down'),
            ('Terminar una relación', 'Break off', 'Look after', 'Get along', 'Turn up', 'Break off'),
            ('Volver a algo', 'Get back to', 'Give up', 'Carry on', 'Put off', 'Get back to'),
            ('Sacar algo a relucir', 'Bring out', 'Put off', 'Call off', 'Show up', 'Bring out'),
            ('Hacer que alguien se sienta mejor', 'Cheer up', 'Give up', 'Turn down', 'Look after', 'Cheer up'),
            ('Buscar información', 'Look up', 'Drop off', 'Set up', 'Carry on', 'Look up'),
            ('Estar de acuerdo con alguien', 'Go along with', 'Break up', 'Get along', 'Turn down', 'Go along with'),
            ('Sustituir algo', 'Replace with', 'Put off', 'Take on', 'Call off', 'Replace with'),
            ('Tratar de hacer algo', 'Try out', 'Give up', 'Put off', 'Carry on', 'Try out'),
            ('Tomar un descanso', 'Take a break', 'Get along', 'Carry on', 'Look after', 'Take a break'),
            ('Encontrar la solución', 'Work out', 'Look after', 'Turn down', 'Pick up', 'Work out'),
            ('Terminar un proyecto', 'Finish up', 'Carry on', 'Look after', 'Set up', 'Finish up'),
            ('Enfocarse en algo', 'Focus on', 'Turn down', 'Get along', 'Call off', 'Focus on'),
            ('Estar al tanto', 'Keep up with', 'Give up', 'Put off', 'Come up', 'Keep up with'),
            ('Comenzar a disfrutar de algo', 'Warm up to', 'Back down', 'Give up', 'Turn down', 'Warm up to'),
            ('Compensar por algo', 'Make up for', 'Break down', 'Look after', 'Carry on', 'Make up for'),
            ('Asumir la responsabilidad', 'Take on', 'Give up', 'Look after', 'Put off', 'Take on'),
            ('Hacer que algo suceda', 'Bring about', 'Look after', 'Turn up', 'Put off', 'Bring about'),
            ('Deshacerse de algo', 'Get rid of', 'Bring up', 'Turn down', 'Back down', 'Get rid of'),
            ('Hacer que alguien se sienta cómodo', 'Put at ease', 'Give up', 'Set up', 'Turn up', 'Put at ease'),
            ('Limitar algo', 'Cut back on', 'Put off', 'Look after', 'Carry on', 'Cut back on'),
            ('Hacer que algo empiece a funcionar', 'Get going', 'Give up', 'Turn down', 'Call off', 'Get going'),
            ('Bajar el volumen', 'Turn down', 'Bring up', 'Call off', 'Set up', 'Turn down'),
            ('Iniciar un negocio', 'Start up', 'Carry on', 'Turn down', 'Look after', 'Start up'),
            ('Dar a entender', 'Point out', 'Drop off', 'Look after', 'Break down', 'Point out'),
            ('Rendir cuentas', 'Account for', 'Carry on', 'Look after', 'Get along', 'Account for'),
            ('Romperse', 'Break down', 'Give up', 'Set up', 'Turn out', 'Break down'),
            ('Esperar a alguien', 'Wait for', 'Look after', 'Carry on', 'Turn down', 'Wait for'),
            ('Escaparse de un lugar', 'Get away', 'Drop off', 'Turn down', 'Give up', 'Get away'),
            ('Despertar el interés', 'Bring to light', 'Call off', 'Look after', 'Turn up', 'Bring to light'),
            ('Cambiar de opinión', 'Come around', 'Turn down', 'Look after', 'Get over', 'Come around'),
            ('Hablar con alguien para resolver un problema', 'Sort out', 'Bring up', 'Call off', 'Get along', 'Sort out'),
            ('Deshacerse de algo', 'Throw away', 'Get rid of', 'Drop off', 'Pick up', 'Throw away'),
            ('Volver a un lugar', 'Go back', 'Turn down', 'Look after', 'Get along', 'Go back'),
            ('Revisar algo', 'Look over', 'Get along', 'Give up', 'Set up', 'Look over'),
            ('Despertar', 'Wake up', 'Get down', 'Carry on', 'Bring up', 'Wake up'),
            ('Bajar algo de un lugar alto', 'Take down', 'Bring up', 'Turn down', 'Pick up', 'Take down'),
            ('Describir algo', 'Go over', 'Turn up', 'Look after', 'Bring about', 'Go over'),
            ('Sacar a alguien de un problema', 'Get out of', 'Give up', 'Look after', 'Carry on', 'Get out of'),
            ('Mejorar la relación con alguien', 'Make up with', 'Bring down', 'Look after', 'Turn up', 'Make up with'),
            ('Dividir algo', 'Break up', 'Get along', 'Set up', 'Call off', 'Break up'),
            ('Contar una historia', 'Tell about', 'Call off', 'Look after', 'Bring up', 'Tell about'),
            ('Despertar la curiosidad', 'Bring out', 'Cut back', 'Turn down', 'Get along', 'Bring out'),
            ('Buscar información', 'Look into', 'Give up', 'Bring up', 'Turn down', 'Look into'),
            ('Recoger algo de un lugar', 'Pick up', 'Put off', 'Look after', 'Give up', 'Pick up'),
            ('Informar sobre algo', 'Report back', 'Bring up', 'Turn down', 'Call off', 'Report back'),
            ('Anotar algo', 'Write down', 'Get along', 'Look after', 'Turn up', 'Write down'),
            ('Dedicarse a una actividad', 'Take up', 'Drop off', 'Look after', 'Give up', 'Take up'),
            ('Dejar que algo pase', 'Let go', 'Hold on', 'Turn down', 'Bring up', 'Let go'),
            ('Organizar algo', 'Set up', 'Look after', 'Call off', 'Bring down', 'Set up'),
            ('Aguantar algo', 'Put up with', 'Get rid of', 'Carry on', 'Turn down', 'Put up with'),
            ('Pasar tiempo con alguien', 'Hang out', 'Turn down', 'Look after', 'Drop off', 'Hang out'),
            ('Deshacerse de algo', 'Get rid of', 'Turn down', 'Pick up', 'Bring up', 'Get rid of'),
            ('Subir algo', 'Turn up', 'Take off', 'Put off', 'Get along', 'Turn up'),
            ('Revisar algo cuidadosamente', 'Go through', 'Look after', 'Carry on', 'Bring up', 'Go through'),
            ('Hacer algo por diversión', 'Mess around', 'Look into', 'Get along', 'Turn down', 'Mess around'),
            ('Asumir una responsabilidad', 'Take on', 'Turn down', 'Get rid of', 'Put off', 'Take on'),
            ('Desarrollar una idea', 'Work out', 'Give up', 'Turn down', 'Bring about', 'Work out'),
            ('Enfrentar algo', 'Face up to', 'Get away with', 'Look after', 'Put off', 'Face up to'),
            ('Regresar a un lugar', 'Come back', 'Take off', 'Turn up', 'Get along', 'Come back'),
            ('Revisar algo rápidamente', 'Skim through', 'Look after', 'Bring up', 'Call off', 'Skim through'),
            ('Aguantar la presión', 'Hold up', 'Carry on', 'Drop off', 'Get over', 'Hold up'),
            ('Acelerar algo', 'Speed up', 'Turn down', 'Set up', 'Give up', 'Speed up'),
            ('Cancelar un evento', 'Call off', 'Look after', 'Bring about', 'Get along', 'Call off'),
            ('Mantener algo', 'Keep up', 'Look into', 'Bring down', 'Get rid of', 'Keep up'),
            ('Alejarse de algo', 'Walk away from', 'Bring up', 'Get along', 'Turn down', 'Walk away from'),
            ('Reconocer un error', 'Own up to', 'Look after', 'Get along', 'Put off', 'Own up to'),
            ('Ajustar algo', 'Tweak', 'Call off', 'Turn down', 'Look after', 'Tweak'),
            ('Buscar ayuda', 'Reach out', 'Bring up', 'Get over', 'Put off', 'Reach out'),
            ('Ser elegido para algo', 'Get picked', 'Call off', 'Give up', 'Turn up', 'Get picked'),
            ('Llevar algo a cabo', 'Carry out', 'Bring up', 'Turn down', 'Get along', 'Carry out'),
            ('Alcanzar a alguien', 'Catch up with', 'Look after', 'Drop off', 'Give up', 'Catch up with'),
            ('Mirar atentamente', 'Check out', 'Turn up', 'Give up', 'Look after', 'Check out'),
            ('Volver a un lugar', 'Go back', 'Look after', 'Bring up', 'Call off', 'Go back'),
            ('Explicar algo', 'Talk through', 'Drop out', 'Carry on', 'Get along', 'Talk through'),
            ('Hacer que algo funcione', 'Sort out', 'Take off', 'Get down', 'Bring about', 'Sort out'),
            ('Escaparse con algo', 'Get away with', 'Give up', 'Look after', 'Put off', 'Get away with'),
            ('Comenzar a hacer algo', 'Take up', 'Call off', 'Look into', 'Give up', 'Take up'),
            ('Pasar por alto algo', 'Brush aside', 'Bring up', 'Turn down', 'Get along', 'Brush aside'),
            ('Levantar algo', 'Pick up', 'Look after', 'Drop off', 'Carry on', 'Pick up'),
            ('Deshacerse de algo', 'Throw away', 'Look after', 'Turn up', 'Give up', 'Throw away'),
            ('Aumentar algo', 'Build up', 'Call off', 'Turn down', 'Drop off', 'Build up'),
            ('Empezar de nuevo', 'Start over', 'Bring up', 'Give up', 'Look after', 'Start over'),
            ('Rechazar una oferta', 'Turn down', 'Get along', 'Drop off', 'Carry on', 'Turn down'),
            ('Continuar después de una interrupción', 'Carry on', 'Call off', 'Get over', 'Put off', 'Carry on'),
            ('Revisar algo', 'Look over', 'Get along', 'Bring up', 'Call off', 'Look over'),
            ('Hacer una pausa', 'Take a break', 'Look after', 'Carry on', 'Get over', 'Take a break'),
            ('Hacer algo más fácil', 'Break down', 'Set up', 'Put off', 'Turn up', 'Break down'),
            ('Aguantar algo', 'Put up with', 'Get along', 'Give up', 'Drop off', 'Put up with'),
            ('Establecer un nuevo lugar', 'Set up', 'Get out', 'Bring up', 'Turn down', 'Set up'),
            ('Enfrentarse a algo', 'Face up to', 'Run into', 'Give up', 'Look after', 'Face up to'),
            ('Despertar a alguien', 'Wake up', 'Pick up', 'Carry on', 'Drop off', 'Wake up'),
            ('Juntarse con alguien', 'Hang out', 'Get along', 'Bring up', 'Take off', 'Hang out'),
            ('Revisar algo cuidadosamente', 'Go over', 'Call off', 'Put off', 'Look after', 'Go over'),
            ('Investigar algo', 'Look into', 'Turn up', 'Bring up', 'Drop off', 'Look into'),
            ('Hacer que alguien se rinda', 'Get to', 'Give in', 'Carry on', 'Take off', 'Give in'),
            ('Comenzar un viaje', 'Set off', 'Look after', 'Get over', 'Carry on', 'Set off'),
            ('Volver a un estado anterior', 'Go back to', 'Bring up', 'Look after', 'Put off', 'Go back to'),
            ('Contar algo', 'Fill in', 'Drop off', 'Look after', 'Turn down', 'Fill in'),
            ('Mostrar sorpresa', 'Blow away', 'Turn up', 'Put off', 'Get along', 'Blow away'),
            ('Aguantar la presión', 'Hold up', 'Take off', 'Give up', 'Carry on', 'Hold up'),
            ('Retirarse de algo', 'Back out', 'Bring up', 'Drop off', 'Look after', 'Back out'),
            ('Recuperarse de algo', 'Get over', 'Look after', 'Put off', 'Turn up', 'Get over'),
            ('Dejar de hacer algo', 'Give up', 'Carry on', 'Bring up', 'Set up', 'Give up'),
            ('Llevar algo a un lugar', 'Take away', 'Put off', 'Look after', 'Run into', 'Take away'),
            ('Crear algo', 'Come up with', 'Bring up', 'Drop off', 'Take off', 'Come up with'),
            ('Admitir algo', 'Own up', 'Give up', 'Take off', 'Look after', 'Own up'),
            ('Ser suficiente', 'Add up', 'Bring up', 'Set up', 'Take off', 'Add up'),
            ('Probar algo', 'Try out', 'Call off', 'Look into', 'Carry on', 'Try out'),
            ('Reunirse con alguien', 'Catch up with', 'Get along', 'Bring up', 'Set up', 'Catch up with'),
            ('Romper algo', 'Break up', 'Put off', 'Get over', 'Look after', 'Break up'),
            ('Hacer que algo ocurra', 'Bring about', 'Turn down', 'Drop off', 'Give up', 'Bring about'),
            ('Encontrar algo por casualidad', 'Come across', 'Put off', 'Look into', 'Get along', 'Come across'),
            ('Preparar algo', 'Get ready', 'Take off', 'Run into', 'Give up', 'Get ready'),
            ('Continuar sin parar', 'Keep on', 'Take off', 'Look after', 'Drop off', 'Keep on'),
            ('Iniciar una conversación', 'Strike up', 'Give in', 'Carry on', 'Look after', 'Strike up'),
            ('Mejorar algo', 'Brush up', 'Bring up', 'Set up', 'Turn down', 'Brush up'),
            ('Finalizar algo', 'Wrap up', 'Drop off', 'Get over', 'Call off', 'Wrap up'),
            ('Aguantar', 'Put up with', 'Give up', 'Carry on', 'Turn up', 'Put up with'),
            ('Estar en desacuerdo', 'Disagree with', 'Run into', 'Break up', 'Call off', 'Disagree with'),
            ('Dejar de lado', 'Put aside', 'Turn down', 'Look into', 'Give up', 'Put aside'),
            ('Invitar a alguien a salir', 'Ask out', 'Bring up', 'Get along', 'Drop off', 'Ask out'),
            ('Atender una llamada', 'Pick up', 'Turn down', 'Put off', 'Take away', 'Pick up'),
            ('Reunir', 'Get together', 'Put up', 'Show off', 'Take off', 'Get together'),
            ('Hacer una pausa', 'Take a break', 'Give in', 'Carry on', 'Break up', 'Take a break'),
            ('Despertar', 'Wake up', 'Drop off', 'Turn out', 'Pick up', 'Wake up'),
            ('Cancelar algo', 'Call off', 'Give up', 'Put off', 'Look after', 'Call off'),
            ('Recuperar algo perdido', 'Get back', 'Look after', 'Give up', 'Turn down', 'Get back'),
            ('Volver a intentar', 'Try again', 'Put off', 'Give in', 'Call off', 'Try again'),
            ('Compartir algo', 'Share out', 'Turn up', 'Keep on', 'Drop off', 'Share out'),
            ('Ver algo de nuevo', 'Look back', 'Get over', 'Carry on', 'Call off', 'Look back'),
            ('Calentar algo', 'Heat up', 'Warm up', 'Set up', 'Put off', 'Heat up'),
            ('Tomar el control', 'Take charge', 'Get along', 'Bring up', 'Keep on', 'Take charge'),
            ('Desaparecer', 'Fade away', 'Break up', 'Come across', 'Turn up', 'Fade away'),
            ('Formar parte de algo', 'Take part in', 'Look after', 'Get over', 'Bring up', 'Take part in'),
            ('Hacer que alguien se sienta bien', 'Lift up', 'Bring down', 'Put down', 'Call off', 'Lift up'),
            ('Hacer un esfuerzo', 'Make an effort', 'Take it easy', 'Break down', 'Give up', 'Make an effort'),
            ('Poner en práctica', 'Put into practice', 'Call off', 'Carry on', 'Look into', 'Put into practice'),
            ('Caer en un error', 'Fall for', 'Run into', 'Take off', 'Get along', 'Fall for'),
            ('Recuperar fuerzas', 'Bounce back', 'Give up', 'Give in', 'Carry on', 'Bounce back'),
            ('Limpiar', 'Clean up', 'Put off', 'Turn down', 'Pick up', 'Clean up'),
            ('Hablar sobre algo', 'Talk about', 'Bring up', 'Call off', 'Look after', 'Talk about'),
            ('Pedir ayuda', 'Ask for help', 'Put up with', 'Get over', 'Look into', 'Ask for help'),
            ('Pasar tiempo', 'Hang out', 'Drop by', 'Turn out', 'Give in', 'Hang out'),
            ('Aprovechar una oportunidad', 'Take advantage of', 'Look into', 'Break down', 'Call off', 'Take advantage of'),
            ('Discutir', 'Talk over', 'Look after', 'Get along', 'Run into', 'Talk over'),
            ('Tomar el control de', 'Take over', 'Put off', 'Run into', 'Give up', 'Take over'),
            ('Iniciar un proyecto', 'Set up', 'Call off', 'Put aside', 'Turn down', 'Set up'),
            ('Terminar con alguien', 'Break up with', 'Get over', 'Look after', 'Carry on', 'Break up with'),
            ('Darse cuenta', 'Realize', 'Find out', 'Turn down', 'Bring up', 'Realize'),
            ('Entrar en un lugar', 'Go in', 'Drop off', 'Look after', 'Bring up', 'Go in'),
            ('Contar con alguien', 'Count on', 'Put up with', 'Give in', 'Look into', 'Count on'),
            ('Continuar haciendo algo', 'Keep on', 'Break down', 'Get over', 'Look after', 'Keep on'),
            ('Llevar a cabo', 'Carry out', 'Turn down', 'Put aside', 'Bring up', 'Carry out'),
            ('Enfrentar a alguien', 'Stand up to', 'Back down', 'Give up', 'Turn down', 'Stand up to'),
            ('Perder el tiempo', 'Waste time', 'Run out of', 'Turn up', 'Look for', 'Waste time'),
            ('Romper con alguien', 'Break up', 'Make up', 'Get along', 'Come across', 'Break up'),
            ('Revisar algo', 'Go over', 'Look after', 'Give up', 'Put off', 'Go over'),
            ('Enviar a alguien a un lugar', 'Send off', 'Turn up', 'Pick up', 'Drop off', 'Send off'),
            ('Despertar a alguien', 'Wake up', 'Drop off', 'Turn down', 'Get along', 'Wake up'),
            ('Comenzar a hacer algo', 'Take up', 'Put off', 'Break down', 'Give up', 'Take up'),
            ('Aprovechar una oportunidad', 'Take advantage of', 'Call off', 'Look into', 'Bring up', 'Take advantage of'),
            ('Preparar algo', 'Get ready', 'Look after', 'Call off', 'Put down', 'Get ready'),
            ('Desaparecer de la vista', 'Fade away', 'Break down', 'Get along', 'Show up', 'Fade away'),
            ('Aplazar algo', 'Put off', 'Call off', 'Get rid of', 'Turn up', 'Put off'),
            ('Confiar en alguien', 'Count on', 'Look for', 'Break down', 'Turn down', 'Count on'),
            ('Reparar algo', 'Fix up', 'Set up', 'Give up', 'Look after', 'Fix up'),
            ('Dejarse llevar', 'Go along with', 'Back down', 'Get rid of', 'Take up', 'Go along with'),
            ('Compensar algo', 'Make up for', 'Give up', 'Drop off', 'Turn down', 'Make up for'),
            ('Revisar de nuevo', 'Check over', 'Look after', 'Break down', 'Put off', 'Check over'),
            ('Resolver un problema', 'Sort out', 'Give up', 'Call off', 'Look after', 'Sort out'),
            ('Terminar una relación', 'Break off', 'Turn down', 'Get along', 'Back up', 'Break off'),
            ('Llevarse bien con alguien', 'Get along with', 'Run into', 'Drop off', 'Take care of', 'Get along with'),
            ('Poner a alguien al corriente', 'Fill in', 'Check out', 'Take over', 'Look into', 'Fill in'),
            ('Buscar información', 'Look into', 'Call off', 'Put off', 'Get over', 'Look into'),
            ('Engañar a alguien', 'Take in', 'Drop off', 'Break up', 'Bring up', 'Take in'),
            ('Atender una emergencia', 'Deal with', 'Take off', 'Give away', 'Look for', 'Deal with'),
            ('Darse por vencido', 'Give in', 'Put up', 'Take on', 'Drop by', 'Give in'),
            ('Acabar con algo', 'Put an end to', 'Get over', 'Carry out', 'Look for', 'Put an end to'),
            ('Tropezarse con alguien', 'Run across', 'Bring down', 'Come up with', 'Give up', 'Run across'),
            ('Llevar algo a cabo', 'Carry out', 'Break off', 'Turn up', 'Look after', 'Carry out'),
            ('Ponerse en marcha', 'Set off', 'Call off', 'Pick up', 'Give up', 'Set off'),
            ('Entregar algo', 'Hand in', 'Put off', 'Take on', 'Turn out', 'Hand in'),
            ('Recoger algo', 'Pick up', 'Show off', 'Set up', 'Give in', 'Pick up'),
            ('Continuar con algo', 'Go ahead', 'Get along', 'Break down', 'Take off', 'Go ahead'),
            ('Soportar algo difícil', 'Put up with', 'Run out of', 'Turn down', 'Give away', 'Put up with'),
            ('Desmoronarse emocionalmente', 'Break down', 'Set off', 'Pick up', 'Hand out', 'Break down'),
            ('Conseguir algo', 'Get hold of', 'Set off', 'Call out', 'Bring down', 'Get hold of'),
            ('Aparecer sin previo aviso', 'Turn up', 'Take off', 'Look after', 'Break out', 'Turn up'),
            ('Tener éxito', 'Pull off', 'Give in', 'Look into', 'Run out', 'Pull off'),
            ('Romperse en pedazos', 'Fall apart', 'Give up', 'Show up', 'Bring up', 'Fall apart'),
            ('Mantener algo', 'Keep up', 'Look into', 'Take on', 'Break down', 'Keep up'),
            ('Rechazar una oferta', 'Turn down', 'Bring in', 'Call out', 'Pick up', 'Turn down'),
            ('Acostumbrarse a algo', 'Get used to', 'Take off', 'Put on', 'Bring down', 'Get used to'),
            ('Dejar de hacer algo', 'Give up', 'Look after', 'Take on', 'Turn up', 'Give up'),
            ('Esperar con ansias', 'Look forward to', 'Give in', 'Take off', 'Bring up', 'Look forward to'),
            ('Terminar algo abruptamente', 'Break off', 'Bring up', 'Call off', 'Give away', 'Break off'),
            ('Pasar por algo difícil', 'Go through', 'Look up', 'Set up', 'Bring down', 'Go through'),
            ('Encontrarse con dificultades', 'Run into', 'Look forward to', 'Give up', 'Get on with', 'Run into'),
            ('Cerrar un trato', 'Close down', 'Take off', 'Look for', 'Bring down', 'Close down'),
            ('Reducir algo', 'Cut down on', 'Turn down', 'Break up', 'Pick up', 'Cut down on'),
            ('Hacer frente a un problema', 'Face up to', 'Get away', 'Give up', 'Look after', 'Face up to'),
            ('Volverse menos intenso', 'Die down', 'Bring up', 'Turn out', 'Set off', 'Die down'),
            ('Inventar una excusa', 'Make up', 'Get along', 'Turn down', 'Look after', 'Make up'),
            ('Resolver un problema', 'Sort out', 'Look into', 'Give up', 'Take on', 'Sort out'),
            ('Establecerse en un lugar', 'Settle down', 'Give away', 'Take up', 'Bring down', 'Settle down'),
            ('Cortar una conversación', 'Cut off', 'Bring down', 'Take on', 'Look into', 'Cut off'),
            ('Hacer algo con entusiasmo', 'Throw yourself into', 'Put off', 'Turn out', 'Bring up', 'Throw yourself into'),
            ('Evitar responsabilidades', 'Shirk off', 'Look after', 'Put on', 'Take off', 'Shirk off'),
            ('Llevar algo a su fin', 'Wind up', 'Turn down', 'Take up', 'Get along', 'Wind up'),
            ('Pasar por alto algo', 'Overlook', 'Get over', 'Put up', 'Call off', 'Overlook'),
            ('Hablar demasiado de algo', 'Harp on', 'Put on', 'Take up', 'Give in', 'Harp on'),
            ('Desentenderse de algo', 'Back away', 'Give up', 'Set off', 'Look into', 'Back away'),
            ('Renunciar a algo', 'Back out of', 'Bring down', 'Call out', 'Pick up', 'Back out of'),
            ('Volver a intentar algo', 'Try out', 'Come up', 'Turn on', 'Back down', 'Try out'),
            ('Empezar una nueva actividad', 'Take up', 'Break down', 'Carry out', 'Look after', 'Take up'),
            ('Buscar información', 'Look up', 'Give away', 'Turn up', 'Put on', 'Look up'),
            ('Pasar por encima de algo', 'Go over', 'Set up', 'Back down', 'Pick up', 'Go over'),
            ('Descubrir un secreto', 'Find out', 'Make up', 'Get over', 'Give in', 'Find out'),
            ('Hacer un esfuerzo adicional', 'Go out of your way', 'Bring up', 'Come across', 'Get over', 'Go out of your way'),
            ('Continuar después de una pausa', 'Carry on', 'Break down', 'Look into', 'Turn up', 'Carry on'),
            ('Reparar algo', 'Fix up', 'Call off', 'Take up', 'Turn on', 'Fix up'),
            ('Avanzar en algo', 'Get ahead', 'Look after', 'Give up', 'Bring up', 'Get ahead'),
            ('Cancelar algo planeado', 'Call off', 'Bring up', 'Go over', 'Get along', 'Call off'),
            ('Aceptar una responsabilidad', 'Take on', 'Turn down', 'Look after', 'Break down', 'Take on'),
            ('Responder con agresividad', 'Snap back', 'Get along', 'Bring up', 'Turn up', 'Snap back'),
            ('Descartar algo', 'Rule out', 'Turn down', 'Set up', 'Carry on', 'Rule out'),
            ('Quedarse sin algo', 'Run out of', 'Put up with', 'Break out', 'Look up', 'Run out of'),
            ('Deshacerse de algo', 'Get rid of', 'Give up', 'Bring up', 'Take over', 'Get rid of'),
            ('Dejar a alguien quedarse', 'Put up', 'Give away', 'Set up', 'Call off', 'Put up'),
            ('Posponer algo', 'Put off', 'Turn out', 'Carry on', 'Get out', 'Put off'),
            ('Reunirse con alguien', 'Meet up', 'Break down', 'Set up', 'Take off', 'Meet up'),
            ('Soportar algo difícil', 'Put up with', 'Look up', 'Run into', 'Call off', 'Put up with'),
            ('Acostumbrarse a algo', 'Get used to', 'Carry on', 'Set up', 'Give in', 'Get used to'),
            ('Arreglar algo', 'Sort out', 'Give away', 'Get along', 'Bring down', 'Sort out'),
            ('Ignorar un problema', 'Brush off', 'Take on', 'Turn down', 'Give away', 'Brush off'),
            ('Quedarse en casa', 'Stay in', 'Break out', 'Look up', 'Take off', 'Stay in'),
            ('Discutir detalles', 'Hammer out', 'Get along', 'Turn on', 'Put off', 'Hammer out');`
        );   
    }

    db.close();
}

CrearBaseSiNoExiste();

module.exports = CrearBaseSiNoExiste;

//https://www.languageforlife.es/wp-content/uploads/2013/10/Complete-PV-list.pdf